### ISSUE TITLE
Arachne endpoint definitions shall allow handlers that handle all methods

### ISSUE THREAD

**Issue by ordnungswidrig** [arachne-framework/arachne-http#15]
Arachne http endpoints can only be bound to a fixed set of methods. Handlers can only be bound to a fixed set of methods and thus cannot check the request method with their own implementation. I suggest to either make the methods argument optional or provide that special `:any` value to bind a handler to all methods.

**Comment by levand** [comment]
`:any` as a method now works as of 253ac87
